Repository macosui/macos_ui, pull requests merged in 2021-05, with the labels that each got.

#51 Implemented Help Button
  CHANGELOG.md
  example/lib/main.dart
  example/pubspec.lock
  lib/macos_ui.dart
  lib/src/buttons/help_button.dart
  lib/src/buttons/help_button_theme.dart
  lib/src/buttons/switch.dart
  lib/src/styles/macos_theme_data.dart
  lib/src/util.dart
  pubspec.yaml
Labels: enhancement, new widget

#55 Readme update
  README.md
Labels: documentation

#58 Code Improvements
  CHANGELOG.md
  analysis_options.yaml
  example/lib/main.dart
  example/pubspec.lock
  lib/macos_ui.dart
  lib/src/buttons/checkbox.dart
  lib/src/buttons/help_button.dart
  lib/src/buttons/help_button_theme.dart
  lib/src/buttons/push_button.dart
  lib/src/buttons/push_button_theme.dart
  lib/src/buttons/radio_button.dart
  lib/src/buttons/switch.dart
  lib/src/indicators/capacity_indicators.dart
  lib/src/indicators/progress_indicators.dart
  lib/src/indicators/rating_indicator.dart
  lib/src/indicators/relevance_indicator.dart
  lib/src/layout/scaffold.dart
  lib/src/library.dart
  lib/src/macos_app.dart
  lib/src/styles/macos_theme.dart
  lib/src/styles/macos_theme_data.dart
  lib/src/styles/typography.dart
  lib/src/util.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#62 Text field
  CHANGELOG.md
  README.md
  example/lib/main.dart
  example/pubspec.lock
  lib/macos_ui.dart
  lib/src/fields/text_field.dart
  lib/src/library.dart
  lib/src/styles/colors.dart
  pubspec.yaml
Labels: enhancement, new widget

#68 Implement Tooltip
  CHANGELOG.md
  README.md
  example/lib/main.dart
  lib/macos_ui.dart
  lib/src/labels/tooltip.dart
  lib/src/library.dart
  lib/src/styles/macos_theme_data.dart
Labels: new widget

#72 Update Scaffold images
  README.md
  lib/src/labels/tooltip.dart
  pubspec.lock
  pubspec.yaml
Labels: documentation

#75 Adjust failing score
  .github/workflows/pana_analysis.yml
  lib/src/labels/tooltip.dart
Labels: repo

#93 Implement Label
  CHANGELOG.md
  example/lib/main.dart
  lib/macos_ui.dart
  lib/src/labels/label.dart
  lib/src/library.dart
Labels: new widget

#94 Theme update
  CHANGELOG.md
  example/pubspec.lock
  lib/macos_ui.dart
  lib/src/buttons/checkbox.dart
  lib/src/buttons/help_button.dart
  lib/src/buttons/help_button_theme.dart
  lib/src/buttons/push_button.dart
  lib/src/buttons/push_button_theme.dart
  lib/src/buttons/radio_button.dart
  lib/src/buttons/switch.dart
  lib/src/fields/text_field.dart
  lib/src/indicators/capacity_indicators.dart
  lib/src/indicators/progress_indicators.dart
  lib/src/indicators/rating_indicator.dart
  lib/src/indicators/relevance_indicator.dart
  lib/src/labels/label.dart
  lib/src/labels/tooltip.dart
  lib/src/layout/resizable_pane.dart
  lib/src/layout/scaffold.dart
  lib/src/macos_app.dart
  lib/src/styles/colors.dart
  lib/src/styles/macos_theme.dart
  lib/src/styles/macos_theme_data.dart
  lib/src/styles/typography.dart
  pubspec.yaml
Labels: theme

#113 0.2.2. Macos colors
  CHANGELOG.md
  example/pubspec.lock
  lib/macos_ui.dart
  lib/src/theme/macos_colors.dart
  lib/src/theme/macos_dynamic_color.dart
  pubspec.yaml
Labels: enhancement, theme

#112 Update github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation-update.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new-widget.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/gh_pages.yml
Labels: enhancement

#118 Fix text field
  CHANGELOG.md
  example/lib/main.dart
  example/pubspec.lock
  lib/src/fields/text_field.dart
  pubspec.yaml
Labels: enhancement
