Repository macosui/macos_ui, pull requests merged in 2023-07, with the labels that each got.

#414 feat: Added support for `startWeekOnMonday` to `MacosDatePicker`
  CHANGELOG.md
  lib/src/selectors/date_picker.dart
  test/selectors/date_picker_test.dart
Labels: pr:improvment

#415 feat: Added support for `dateFormat` to `MacosDatePicker`
  CHANGELOG.md
  README.md
  lib/src/selectors/date_picker.dart
  test/selectors/date_picker_test.dart
Labels: pr:improvment

#416 feat: Added support for `weekdayAbbreviations` and `monthAbbreviations` to `MacosDatePicker`
  CHANGELOG.md
  README.md
  lib/src/selectors/date_picker.dart
  lib/src/utils.dart
  test/selectors/date_picker_test.dart
Labels: pr:improvment

#441 fix: `ToolBar` title not avoiding traffic lights when no sidebar is present
  CHANGELOG.md
  example/pubspec.lock
  lib/src/layout/window.dart
  pubspec.yaml
Labels: pr:bugfix

#447 feat: implement `ControlSize` for `PushButton`
  .github/workflows/dart_code_metrics.yaml
  CHANGELOG.md
  README.md
  analysis_options.yaml
  example/lib/pages/buttons_page.dart
  example/lib/pages/dialogs_page.dart
  example/pubspec.lock
  lib/src/buttons/push_button.dart
  lib/src/theme/macos_theme.dart
  pubspec.lock
  pubspec.yaml
  test/buttons/push_button_test.dart
  test/theme/push_button_theme_test.dart
Labels: pr:improvment, pr:widget

#448 fix: checkbox appearance
  CHANGELOG.md
  example/lib/pages/buttons_page.dart
  example/pubspec.lock
  lib/src/buttons/checkbox.dart
  pubspec.yaml
  test/buttons/checkbox_test.dart
Labels: pr:improvment, pr:widget

#420 Non-scrollable `ResizablePane`
  CHANGELOG.md
  example/lib/pages/resizable_pane_page.dart
  example/lib/widgets/widget_text_title1.dart
  example/pubspec.lock
  lib/src/layout/resizable_pane.dart
  pubspec.yaml
  test/layout/resizeable_pane_test.dart
  test/selectors/date_picker_test.dart
Labels: waiting for customer response, pr:improvment

#460 Fix broken web support, platform theming issues, and typography updates
  CHANGELOG.md
  example/lib/main.dart
  example/lib/pages/selectors_page.dart
  example/lib/platform_menus.dart
  example/macos/Flutter/GeneratedPluginRegistrant.swift
  example/macos/Podfile.lock
  example/pubspec.lock
  example/pubspec.yaml
  lib/src/buttons/push_button.dart
  lib/src/layout/scaffold.dart
  lib/src/layout/toolbar/toolbar.dart
  lib/src/layout/window.dart
  lib/src/theme/macos_theme.dart
  lib/src/theme/typography.dart
  lib/src/utils.dart
  pubspec.yaml
Labels: pr:bugfix

#461 2.0: Readme updates
  CHANGELOG.md
  README.md
  example/lib/pages/buttons_page.dart
  example/lib/pages/dialogs_page.dart
  example/lib/pages/indicators_page.dart
  example/pubspec.lock
  lib/src/buttons/help_button.dart
  lib/src/indicators/relevance_indicator.dart
  pubspec.yaml
  test/indicators/relevance_indicator_test.dart
Labels: pr:widget, pr:docs
